const SET_TOKEN = 'SET_TOKEN';
const GET_DATA = 'GET_DATA';
const SET_USER = 'SET_USER';
const SET_ATTENDANCE = 'SET_ATTENDANCE';
const SHOW_BACKDROP = 'SHOW_BACKDROP';
const HIDE_BACKDROP = 'HIDE_BACKDROP';
const SET_ERRORS = 'SET_ERRORS';
const SET_HISTORY = 'SET_HISTORY'
const SET_CONVERSATION = 'SET_CONVERSATION'
const SET_NOTIFICATION= 'SET_NOTIFICATION'
/////////////////
const SET_ALL_USERS = 'SET_ALL_USERS';
const SET_MY_USER = 'SET_MY_USER';
const SET_REGISTEREDUSERS = 'SET_REGISTEREDUSERS';


export {
    SET_TOKEN,
    SET_USER,
    SHOW_BACKDROP,
    HIDE_BACKDROP,
    GET_DATA,
    SET_ERRORS,
    SET_ATTENDANCE,
    SET_HISTORY,
    SET_CONVERSATION,
    SET_NOTIFICATION,

    SET_ALL_USERS,
    SET_MY_USER,
    SET_REGISTEREDUSERS

    
}