
const SET_TOKEN = 'SET_TOKEN';
const SET_STATUS = 'SET_STATUS'
const LOG_IN = 'LOG_IN';
const REMOVE_TOKEN = 'REMOVE_TOKEN';
const GET_DATA = 'GET_DATA';
const SET_USER = 'SET_USER';

const SET_ERRORS = 'SET_ERRORS';
const SET_HISTORY = 'SET_HISTORY'
const SET_CONVERSATION = 'SET_CONVERSATION'
const SET_NOTIFICATION= 'SET_NOTIFICATION'
const SET_UNSEEN_MSGS= 'SET_UNSEEN_MSGS'
const INC_UNSEEN_MSGS= 'INC_UNSEEN_MSGS'
const DEC_UNSEEN_MSGS= 'DEC_UNSEEN_MSGS'
/////////////////
const SET_ALL_USERS = 'SET_ALL_USERS';
const SET_REGISTEREDUSERS = 'SET_REGISTEREDUSERS';
const SET_MYINBOX = 'SET_MYINBOX';
const SET_MYCHAT = 'SET_MYCHAT';


export {
    SET_TOKEN,
    SET_STATUS,
    LOG_IN,
    REMOVE_TOKEN,
    SET_USER,
    GET_DATA,
    SET_ERRORS,
    SET_HISTORY,
    SET_CONVERSATION,
    SET_NOTIFICATION,
    SET_UNSEEN_MSGS,
    INC_UNSEEN_MSGS,
    DEC_UNSEEN_MSGS,
    
    SET_ALL_USERS,
    SET_REGISTEREDUSERS,
    SET_MYINBOX,
    SET_MYCHAT,

    
}